export const GET_LISTOFCONTENTS_IS_LOADING = "GET_LISTOFCONTENTS_IS_LOADING";
export const GET_LISTOFCONTENTS_IS_SUCCESS = "GET_LISTOFCONTENTS_IS_SUCCESS";
export const GET_LISTOFCONTENTS_IS_FAILURE = "GET_LISTOFCONTENTS_IS_FAILURE";

export const GET_PLAYLISTS_IS_LOADING = "GET_PLAYLISTS_IS_LOADING";
export const GET_PLAYLISTS_IS_SUCCESS = "GET_PLAYLISTS_IS_SUCCESS";
export const GET_PLAYLISTS_IS_FAILURE = "GET_PLAYLISTS_IS_FAILURE";

export const GET_TOPPLAYLISTS_IS_LOADING = "GET_TOPPLAYLISTS_IS_LOADING";
export const GET_TOPPLAYLISTS_IS_SUCCESS = "GET_TOPPLAYLISTS_IS_SUCCESS";
export const GET_TOPPLAYLISTS_IS_FAILURE = "GET_TOPPLAYLISTS_IS_FAILURE";

export const GET_OTTLIST_IS_LOADING = "GET_OTTLIST_IS_LOADING";
export const GET_OTTLIST_IS_SUCCESS = "GET_OTTLIST_IS_SUCCESS";
export const GET_OTTLIST_IS_FAILURE = "GET_OTTLIST_IS_FAILURE";
